name: deploy to cloudflare

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 * * * *'

jobs:
    deploy:
        name: deploy to cloudflare
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install UV
              # https://docs.astral.sh/uv/guides/integration/github/#setting-up-python
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

            - name: Compile and run yaml generator
              run: | 
                    sudo apt update && sudo apt install libsqlite3-dev
                    git clone https://github.com/Zigistry/dictionary-and-yaml-creator.git
                    cd ./dictionary-and-yaml-creator/
                    gcc ./main.c -lsqlite3
                    wget -O ./zigistry.db https://huggingface.co/buckets/Zigistry/Zigistry/resolve/zigistry.db?download=true
                    ./a.out
                    cp ./sitemap.xml ../static/
            - name: run the dependence dependencies
              run: |
                    git clone https://github.com/Zigistry/dependency-dependent-graph.git
                    cd ./dependency-dependent-graph
                    wget -O ./zigistry.db https://huggingface.co/buckets/Zigistry/Zigistry/resolve/zigistry.db?download=true
                    uv sync
                    uv run ./main.py
                    
            - name: install dependencies
              run: bun install

            - name: build
              run: bun run build

            - name: deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  command: pages deploy ./cloudflare/build --project-name=zigistryok
